name: Build Geode Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake ninja-build clang git

      - name: Clone Geode SDK
        run: git clone --recursive https://github.com/geode-sdk/geode.git

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod
          path: build
